FROM apache/airflow:2.7.3-python3.11

ARG AIRFLOW_CONSTRAINTS_URL=https://raw.githubusercontent.com/apache/airflow/constraints-2.7.3/constraints-3.11.txt

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir --constraint "${AIRFLOW_CONSTRAINTS_URL}" \
    apache-airflow-providers-postgres==5.7.1 \
    requests==2.31.0 \
    python-dateutil==2.8.2 \
    "pandas>=2.0,<3" \
    "openpyxl>=3.1,<4"

# pyarrow y Google se instalan sin constraints para evitar conflictos de versiones
RUN pip install --no-cache-dir \
    "pyarrow>=14,<22" \
    "google-auth>=2.20,<3" \
    "google-auth-httplib2>=0.2,<1" \
    "google-api-python-client>=2.90,<3"
